{
	TFile * ifile_old = new TFile("xt.100002.Garfield.root");
	TFile * ifile_new = new TFile("xt.100002.0111.i6.root");

	TH2D * h2_xt = (TH2D*) ifile_new->Get("h2_xt_4");
	TH2D * h2_xtn = (TH2D*) ifile_new->Get("h2_xtn_4");

	TF1 * f_b_old = (TF1*) ifile_old->Get("fbc_4");
	TF1 * f_l_old = (TF1*) ifile_old->Get("flc_4");
	TF1 * f_r_old = (TF1*) ifile_old->Get("frc_4");
	TF1 * f_b_new = (TF1*) ifile_new->Get("fbc_4");
	TF1 * f_l_new = (TF1*) ifile_new->Get("flc_4");
	TF1 * f_r_new = (TF1*) ifile_new->Get("frc_4");
	if (!f_b_old) f_b_old = (TF1*) ifile_old->Get("fr_0");
	if (!f_l_old) f_l_old = (TF1*) ifile_old->Get("fl_0");
	if (!f_r_old) f_r_old = (TF1*) ifile_old->Get("fr_0");
	if (!f_b_new) f_b_new = (TF1*) ifile_new->Get("fr_0");
	if (!f_l_new) f_l_new = (TF1*) ifile_new->Get("fl_0");
	if (!f_r_new) f_r_new = (TF1*) ifile_new->Get("fr_0");
	if(f_b_old) f_b_old->SetName("ofbc_4");
	if(f_l_old) f_l_old->SetName("oflc_4");
	if(f_r_old) f_r_old->SetName("ofrc_4");
	TF1 * f_b_delta = 0;
	TF1 * f_l_delta = 0;
	TF1 * f_r_delta = 0;
	if(f_b_new&&f_b_old) f_b_delta = new TF1("dfbc_4","fbc_4-ofbc_4",-25,800);
	if(f_l_new&&f_l_old) f_l_delta = new TF1("dflc_4","flc_4-oflc_4",-25,800);
	if(f_r_new&&f_r_old) f_r_delta = new TF1("dfrc_4","frc_4-ofrc_4",-25,800);

	TGraph * gr_bc_old = (TGraph*) ifile_old->Get("gr_xt_bce_4");
	TGraph * gr_bc_new = (TGraph*) ifile_new->Get("gr_xt_bce_4");
	TGraph * gr_rc_old = (TGraph*) ifile_old->Get("gr_xt_rce_4");
	TGraph * gr_rc_new = (TGraph*) ifile_new->Get("gr_xt_rce_4");
	TGraph * gr_lc_old = (TGraph*) ifile_old->Get("gr_xt_lce_4");
	TGraph * gr_lc_new = (TGraph*) ifile_new->Get("gr_xt_lce_4");
	TGraph * gr_bm_old = (TGraph*) ifile_old->Get("gr_xt_bm_4");
	TGraph * gr_bm_new = (TGraph*) ifile_new->Get("gr_xt_bm_4");
	TGraph * gr_rm_old = (TGraph*) ifile_old->Get("gr_xt_rm_4");
	TGraph * gr_rm_new = (TGraph*) ifile_new->Get("gr_xt_rm_4");
	TGraph * gr_lm_old = (TGraph*) ifile_old->Get("gr_xt_lm_4");
	TGraph * gr_lm_new = (TGraph*) ifile_new->Get("gr_xt_lm_4");
	TGraph * gr_be_old = (TGraph*) ifile_old->Get("gr_xt_be_4");
	TGraph * gr_be_new = (TGraph*) ifile_new->Get("gr_xt_be_4");
	TGraph * gr_re_old = (TGraph*) ifile_old->Get("gr_xt_re_4");
	TGraph * gr_re_new = (TGraph*) ifile_new->Get("gr_xt_re_4");
	TGraph * gr_le_old = (TGraph*) ifile_old->Get("gr_xt_le_4");
	TGraph * gr_le_new = (TGraph*) ifile_new->Get("gr_xt_le_4");
	if(gr_bm_old) gr_bm_old->Print();
	if(gr_bm_new) gr_bm_new->Print();
	int nEntries_bm = 0;
	if (gr_bm_old&&gr_bm_new) gr_bm_old->GetN()>gr_bm_new->GetN()?gr_bm_new->GetN():gr_bm_old->GetN();
	TGraph * gr_bm_delta = new TGraph();
	if(gr_bm_delta) gr_bm_delta->Set(nEntries_bm);
	for (int i = 0; i<nEntries_bm; i++){
		double x,y1,y2;
		gr_bm_old->GetPoint(i,x,y1);
		gr_bm_new->GetPoint(i,x,y2);
		gr_bm_delta->SetPoint(i,x,y2-y1);
	}

	if (gr_bc_old) gr_bc_old->SetMarkerSize(1);
	if (gr_rc_old) gr_rc_old->SetMarkerSize(1);
	if (gr_lc_old) gr_lc_old->SetMarkerSize(1);
	if (gr_bc_old) gr_bc_old->SetMarkerStyle(4);
	if (gr_rc_old) gr_rc_old->SetMarkerStyle(4);
	if (gr_lc_old) gr_lc_old->SetMarkerStyle(4);
	if (gr_bc_new) gr_bc_new->SetMarkerSize(0.8);
	if (gr_rc_new) gr_rc_new->SetMarkerSize(0.8);
	if (gr_lc_new) gr_lc_new->SetMarkerSize(0.8);
	if(gr_bm_delta) gr_bm_delta->SetMarkerSize(1);
	if(gr_bm_old) gr_bm_old->SetMarkerSize(1);
	if(gr_rm_old) gr_rm_old->SetMarkerSize(1);
	if(gr_lm_old) gr_lm_old->SetMarkerSize(1);
	if(gr_bm_delta) gr_bm_delta->SetMarkerStyle(4);
	if(gr_bm_old) gr_bm_old->SetMarkerStyle(4);
	if(gr_rm_old) gr_rm_old->SetMarkerStyle(4);
	if(gr_lm_old) gr_lm_old->SetMarkerStyle(4);
	if(gr_bm_delta) gr_bm_delta->SetMarkerSize(0.8);
	if(gr_bm_new) gr_bm_new->SetMarkerSize(0.8);
	if(gr_rm_new) gr_rm_new->SetMarkerSize(0.8);
	if(gr_lm_new) gr_lm_new->SetMarkerSize(0.8);
	if(gr_be_old) gr_be_old->SetMarkerSize(1);
	if(gr_re_old) gr_re_old->SetMarkerSize(1);
	if(gr_le_old) gr_le_old->SetMarkerSize(1);
	if(gr_be_old) gr_be_old->SetMarkerStyle(4);
	if(gr_re_old) gr_re_old->SetMarkerStyle(4);
	if(gr_le_old) gr_le_old->SetMarkerStyle(4);
	if(gr_be_new) gr_be_new->SetMarkerSize(0.8);
	if(gr_re_new) gr_re_new->SetMarkerSize(0.8);
	if(gr_le_new) gr_le_new->SetMarkerSize(0.8);

	if(f_b_old) f_b_old->SetLineColor(kBlack);
	if(f_b_new) f_b_new->SetLineColor(kRed);
	if(f_l_old) f_l_old->SetLineColor(kBlack);
	if(f_l_new) f_l_new->SetLineColor(kMagenta);
	if(f_r_old) f_r_old->SetLineColor(kBlack);
	if(f_r_new) f_r_new->SetLineColor(kRed);
	if (gr_bc_old) gr_bc_old->SetMarkerColor(kBlack);
	if (gr_bc_new) gr_bc_new->SetMarkerColor(kRed);
	if (gr_rc_old) gr_rc_old->SetMarkerColor(kBlack);
	if (gr_rc_new) gr_rc_new->SetMarkerColor(kRed);
	if (gr_lc_old) gr_lc_old->SetMarkerColor(kBlack);
	if (gr_lc_new) gr_lc_new->SetMarkerColor(kMagenta);
	if(gr_bm_old) gr_bm_old->SetMarkerColor(kBlack);
	if(gr_bm_new) gr_bm_new->SetMarkerColor(kRed);
	if(gr_rm_old) gr_rm_old->SetMarkerColor(kBlack);
	if(gr_rm_new) gr_rm_new->SetMarkerColor(kRed);
	if(gr_lm_old) gr_lm_old->SetMarkerColor(kBlack);
	if(gr_lm_new) gr_lm_new->SetMarkerColor(kMagenta);
	if(gr_be_old) gr_be_old->SetMarkerColor(kBlack);
	if(gr_be_new) gr_be_new->SetMarkerColor(kRed);
	if(gr_re_old) gr_re_old->SetMarkerColor(kBlack);
	if(gr_re_new) gr_re_new->SetMarkerColor(kRed);
	if(gr_le_old) gr_le_old->SetMarkerColor(kBlack);
	if(gr_le_new) gr_le_new->SetMarkerColor(kMagenta);

	new TCanvas();
	if(h2_xtn) h2_xtn->Draw("COLZ");
	if (gr_bc_old) gr_bc_old->Draw("PSAME");
	if(gr_bm_old) gr_bm_old->Draw("PSAME");
	if(gr_be_old) gr_be_old->Draw("PSAME");
	if (gr_bc_new) gr_bc_new->Draw("PSAME");
	if(gr_bm_new) gr_bm_new->Draw("PSAME");
	if(gr_be_new) gr_be_new->Draw("PSAME");
	if(f_b_old) f_b_old->Draw("same");
	if(f_b_new) f_b_new->Draw("same");
	new TCanvas();
	if(h2_xt) h2_xt->Draw("COLZ");
	if (gr_rc_old) gr_rc_old->Draw("PSAME");
	if(gr_rm_old) gr_rm_old->Draw("PSAME");
	if(gr_re_old) gr_re_old->Draw("PSAME");
	if (gr_rc_new) gr_rc_new->Draw("PSAME");
	if(gr_rm_new) gr_rm_new->Draw("PSAME");
	if(gr_re_new) gr_re_new->Draw("PSAME");
	if(f_r_old) f_r_old->Draw("same");
	if(f_r_new) f_r_new->Draw("same");
	if (gr_lc_old) gr_lc_old->Draw("PSAME");
	if(gr_lm_old) gr_lm_old->Draw("PSAME");
	if(gr_le_old) gr_le_old->Draw("PSAME");
	if (gr_lc_new) gr_lc_new->Draw("PSAME");
	if(gr_lm_new) gr_lm_new->Draw("PSAME");
	if(gr_le_new) gr_le_new->Draw("PSAME");
	if(f_l_old) f_l_old->Draw("same");
	if(f_l_new) f_l_new->Draw("same");

	new TCanvas();
	if(f_l_delta) f_l_delta->Draw();
	new TCanvas();
	if(f_r_delta) f_r_delta->Draw();
	new TCanvas();
	if(f_b_delta) f_b_delta->Draw();
	if(gr_bm_delta) gr_bm_delta->Draw("PSAME");
}
